BEGIN;

ALTER TABLE public.schedules
  ADD COLUMN IF NOT EXISTS dealer_name      TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS location         TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS instructor       TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS target_audience  TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS manager_name     TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS is_soft_deleted  BOOLEAN DEFAULT FALSE;

COMMIT;
